name = "logging-do"
route = { pattern = "*/*", zone_name = "logging.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-27"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

[durable_objects]
bindings = [{name = "LOGGER", class_name = "Logger"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Logger"]
